local modded_units = {
{"ovn_arb_inf_sharkas_slaves", "core"},
{"ovn_arb_inf_arabyan_warriors", "core"},
{"ovn_arb_inf_arabyan_warriors_ror", "core"},
{"ovn_arb_inf_arabyan_spearmen", "core"},
{"ovn_arb_inf_arabyan_bowmen", "core"},
{"ovn_arb_inf_naffatun_ror", "core"},
{"ovn_arb_inf_pit_fighters", "core"},
{"ovn_arb_inf_corsairs", "core"},
{"ovn_arb_cav_bedouin_scouts", "core"},
{"ovn_arb_cav_lancer_camels", "core"},
{"ovn_arb_cav_lancer_camels_ror", "core"},
{"ovn_arb_cav_archer_camels", "core"},
{"ovn_arb_cav_arabyan_knights", "core"},
{"ovn_arb_cav_arabyan_knights_ror", "core"},
{"ovn_arb_tze_inf_blue_horrors_0", "core"},
{"ovn_arb_tze_inf_pink_horrors_0", "core"},

{"ovn_arb_inf_arabyan_guard", "special", 1},
{"ovn_arb_inf_arabyan_guard_ror", "special", 1},
{"ovn_arb_inf_dervishers", "special", 1},
{"ovn_arb_inf_southland_warriors", "special", 1},
{"ovn_arb_inf_alrahem_nomads", "special", 1},
{"ovn_arb_inf_jezzails", "special", 1},
{"ovn_arb_inf_jezzails_ror", "special", 1},
{"ovn_arb_cav_jezzail_camels", "special", 1},
{"ovn_arb_cav_sipahis", "special", 2},
{"ovn_arb_cav_sipahis_ror", "special", 2},
{"ovn_arb_cav_flying_carpets", "special", 2},
{"ovn_arb_cav_flying_carpets_ror", "special", 2},
{"ovn_arb_mon_enchanted_rope", "special", 2},
{"ovn_arb_mon_genie", "special", 3},
{"ovn_arb_mon_elephant", "special", 2},
{"ovn_arb_tze_mon_screamers_0", "special", 1},
{"ovn_arb_tze_mon_flamers_0", "special", 2},
{"ovn_arb_tmb_mon_ushabti_0", "special", 2},
{"ovn_arb_tmb_mon_ushabti_1", "special", 2},

{"ovn_arb_cav_waghzen", "rare", 1},
{"ovn_arb_mon_war_elephant", "rare", 2},
{"ovn_arb_mon_war_elephant_ror_1", "rare", 3},
{"ovn_arb_mon_war_elephant_ror_2", "rare", 2},
{"ovn_arb_mon_desert_spirit", "rare", 3},
{"ovn_arb_mon_desert_spirit_ror", "rare", 3},
{"ovn_arb_mon_fire_efreet", "rare", 3},
{"ovn_arb_mon_fire_efreet_ror", "rare", 3},
{"ovn_arb_mon_sea_nymph", "rare", 3},
{"ovn_arb_mon_sea_nymph_ror", "rare", 3},
{"ovn_arb_mon_tempest_djinn", "rare", 3},
{"ovn_arb_mon_tempest_djinn_ror", "rare", 3},
{"ovn_arb_mon_giant_vulture_feral", "rare", 1},
{"ovn_arb_djinn_carriage", "rare", 3},
{"ovn_arb_art_quadballista", "rare", 1},
{"ovn_arb_art_quadballista_ror", "rare", 1},
{"ovn_arb_art_grand_bombard", "rare", 1},
{"ovn_arb_art_grand_bombard_ror", "rare", 1},
{"ovn_arb_tze_mon_lord_of_change_0", "rare", 3},
{"ovn_arb_tmb_mon_heirotitan_0", "rare", 3},
{"ovn_arb_tmb_mon_necrosphinx_0", "rare", 3},
{"ovn_arb_tmb_veh_khemrian_warsphinx_0", "rare", 2},
{"ovn_arb_art_naphtha_thrower", "rare", 2},
{"ovn_arb_veh_naphtha_thrower_ror", "rare", 3}
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(modded_units)
    end)
end